### ISSUE TITLE
Buildings must have stats

### ISSUE THREAD

**Issue by EffettoNeve** [sensorario/yagolands-client#2]
Buildings must show their stats to player: units produced per hour, resources produced per hour, upgrade requirements, etc.

**Comment by sensorario** [comment]
Ciao @EffettoNeve. Manca ancora molta complessità nel nocciolo del gioco. La grafica è pressoché assente. Ho realizzato un altro progettino dedicato al client. Attualmente la poverissima interfaccia si presenta cosi: con qualche dato statistico ed un singolo misero bottone che da il via alle costruzioni.

<img width="169" alt="Schermata 2022-07-17 alle 01 07 50" src="https://user-images.githubusercontent.com/820248/179374562-42f9fd19-9cbc-430a-bb8a-3727909e6018.png">

Quando parte la costruzione, ... il timer mostra il countdown.

<img width="334" alt="Schermata 2022-07-17 alle 01 07 57" src="https://user-images.githubusercontent.com/820248/179374565-9cff1e62-b0ff-498a-9e4a-84044240591e.png">
 
Per i dati che ho adesso mi aspetterei la possibilità di vedere la scheda dell'edificio con immagine, magari, e con le risorse necessarie alla costruzione. Tempo necessario per terminare un ampliamento, se l'ampliamento è in corso. E cosi via. C'è qualche gioco al quale ci si potrebbe ispirare? Riusciamo a trovare qualche screenshot?

**Comment by EffettoNeve** [comment]
Sicuramente Forge of Empires.
Poi OGame.

Infine, State of Survival: Zombie War.
L'ho cancellato da poco, ma è il più recente. Prenderei questo come esempio.
Screenshot:
https://i0.wp.com/freewargamer.com/wp-content/uploads/2019/11/state-of-survival-outpost.jpg?fit=1200%2C675&ssl=1
